### PR TITLE
Refactored most of the part of the plugin and added common used commands

### PR DESCRIPTION
**Pull request by wenqiangwang**
Please feel free to pull it to the origin branch and let me you know your feedback.

### CODE REVIEW

**Comment by joshnajera** [comment]
Dude! This is awesome!!

**Comment by wenqiangwang** [comment]
Thanks! Glad to contribute.

BTW, I think i messed the Readme.md. Please update if you want. Also I fogot to comment out the DEBUGING=1 line which will print out a bunch of messages to console.

I am sure there should be a bunch of bugs. I will send PRs along the way when I fix them.

**Comment by joshnajera** [comment]
I really appreciate that you PR'd! lol :)
I am also very happy you got some of the features I couldn't!

I will try and learn from your code.

I changed DEBUGGING to 0, and submitted a new release to the asset library!

**Comment by wenqiangwang** [comment]
No worries. It's so hard for me to type in Godot without VIM. While VSCode works but it it's much nicer to type right within Godot. So I have been looking for solutions and until one day find your project. You inspired me that this can be fully done in Godot!

**Pull request merged**
